name: Terraform workflow

on: [push]

jobs:
  terraform:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0
    
    - name: Terraform Format Checkout
      run: terraform fmt -check -recursive

    - name: Terraform init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate
    
    - name: Setup tflint
      uses: terraform-linters/setup-tflint@v1
    
    - name: Run tflint
      run: tflint

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
